### ISSUE TITLE
PHPUnit Code Coverage

### ISSUE THREAD

**Issue by BrianHenryIE** [pablo-pacheco/wp-namespace-autoloader#4]
I tried this on a project but my PHPUnit code coverage began reporting 0% code coverage. Once I used `require_once` for each class, it began working again. Is there a sample project I can follow so I know I have it configured correctly.

**Comment by pablo-sg-pacheco** [comment]
Hello,

Hum, I haven't tried it yet with PHPUnit.
Can you please check these 2 questions for now?

- https://stackoverflow.com/questions/28028657/phpunit-code-coverage-for-abstract-class-at-0-even-though-its-clearly-tested

- https://stackoverflow.com/questions/25219764/phpunit-autoload-classes-within-tests

Can you please also check if your files, folders and namespaces are correct?
But in the end, I'm afraid it might doesn't work because I think PHPUnit will use the default PSR naming conventions :(

**Comment by BrianHenryIE** [comment]
Thanks. It was the case-sensitivity of the file-system/folder names. Once I renamed the folders to have capital letters matching the namespace names, it worked again.

**Comment by BrianHenryIE** [comment]
I've uploaded my code here, it might be useful for others to see as an example.
https://github.com/BrianHenryIE/BH-WP-Autologin-URLs

**Comment by pablo-sg-pacheco** [comment]
Oh, thanks!

**Comment by pablo-sg-pacheco** [comment]
A question @BrianHenryIE , why didn't you use it with Composer?

**Comment by BrianHenryIE** [comment]
I’m only using composer for my dev environment because often packages don’t use `class_exists` as you do. But also, I made a small change to the code to allow files named `interface-...php` and `abstract-...php` so also changed its namespace. That’s not strictly WPCS or I would’ve made a PR.
